#!/bin/bash

help_msg(){
	
	echo ""
	
	if [ "${1+xxx}" ];
		then
		echo -e $1
		echo ""
	fi
	
	echo -e "\e[36m\e[1m__Personal Blog Manager__\e[0m"
	echo ""
	echo "A utility to help manage and post on my Jekyll blog and push to Github Pages."

	echo ""
	echo -e "\e[38;5;222mUsage Instructions:\e[0m"
	
	echo ""
	echo -e " \e[92mtoday\e[0m" 
	echo "		Opens sublime text with the jekyll project directory."
	echo ""

	echo -e " \e[92mpublish\e[0m" 
	echo -e "		Auto \e[31madd+commit+push\e[0m to Github Pages repository."
	echo ""


	echo -e " \e[92mbuild\e[0m" 
	echo -e "		Build/Complile local Jekyll site."
	echo ""

	echo -e " \e[92mdemo\e[0m" 
	echo -e "		Run Jekyll site locally."
	echo ""

	echo -e "\e[38;5;222mOptional args:\e[0m"
	echo ""
	echo -e " \e[92m-h\e[0m"
	echo "		Help and documentation."
	echo ""
	
}

help(){

	help_msg
	echo ""
	echo -e "\e[1mHelp Text\e[0m"
	echo -e "Lorem ipsum dolor sit amet, consectetur adipisicing elit.\nQuia libero voluptatum veniam laudantium corporis, illo enim"
	echo -e "\nipsa ut voluptatem similique possimus delectus vitae quisquam.\nDistinctio molestias dolor,"
	echo -e "\nsuscipit doloremque ipsa."
	exit 1;

}

if [[ $# -eq 0 ]] ; then
	help_msg
	exit 1;
fi

push(){

	echo "Pushing site to GitHub Pages.."
	echo ""
	cd ~/Blog/blog.abhishekbalam.xyz
	git add .
	git commit -m "$(date)"
	git push
	echo ""
	echo "Now just check the website if the site is updated.. :)"

}

compile(){

	echo "Building Jekyll site."
	echo ""
	cd ~/Blog/blog.abhishekbalam.xyz
	jekyll build

}

serve(){

	echo "Running Jekyll site locally..."
	echo ""
	cd ~/Blog/blog.abhishekbalam.xyz
	jekyll serve --watch 
	xdg-open http://127.0.0.1:4000 &

}


while [ $# -gt 0 ]
do
    case "$1" in
       	today)  subl ~/Blog/blog.abhishekbalam.xyz;;
		publish) push;;
		build) compile;;
		demo) serve;;
		-h)  help;;
		*)  
			help_msg "\e[31m\e[1mWrong arguments!\e[0m"
			exit 1;
			break;
 	esac
    shift
done
