#!/bin/bash

help_msg(){
	
	echo ""
	
	if [ "${1+xxx}" ];
		then
		echo -e $1
		echo ""
	fi
	
	echo -e "\e[36m\e[1m__Personal Blog Manager__\e[0m"
	echo ""
	echo "A utility to help manage and post on my Jekyll blog and push to Github Pages."

	echo ""
	echo -e "\e[38;5;222mUsage Instructions:\e[0m"
	
	echo ""
	echo -e " \e[92m1. post\e[0m" 
	echo "		Opens Sublime Text with new blog post created for today."
	
	echo ""
	echo -e " \e[92m2. note\e[0m" 
	echo "		Opens Sublime Text with new note created for today."
	
	echo -e " \e[92m3. files\e[0m" 
	echo "		Opens Nautilus with the Jekyll project directory."
	
	echo -e " \e[92m4. open\e[0m" 
	echo "		Opens Sublime Text with the Jekyll project directory."
	
	echo -e " \e[92m5. push\e[0m" 
	echo -e "		Auto \e[31madd+commit+push\e[0m to Github Pages repository."
	
	echo -e " \e[92m6. publish\e[0m" 
	echo -e "		Build/Complile + publish via Surge ."

	echo -e " \e[92m7. build\e[0m" 
	echo -e "		Build Jekyll site locally. "

	echo -e " \e[92m8. demo\e[0m" 
	echo -e "		Run Jekyll site locally at http://127.0.0.1:4000 . "

	echo -e " \e[92m9. view\e[0m" 
	echo -e "		View the blog site. "

	echo -e "\e[38;5;222mOptional args:\e[0m"
	echo ""
	echo -e " \e[92m-h\e[0m"
	echo "		Help and documentation."
	echo ""
	
}

help(){

	help_msg
	echo ""
	echo -e "\e[1mHelp Text\e[0m"
	echo -e "Lorem ipsum dolor sit amet, consectetur adipisicing elit.\nQuia libero voluptatum veniam laudantium corporis, illo enim"
	echo -e "\nipsa ut voluptatem similique possimus delectus vitae quisquam.\nDistinctio molestias dolor,"
	echo -e "\nsuscipit doloremque ipsa."
	exit 1;

}

if [[ $# -eq 0 ]] ; then
	help_msg
	exit 1;
fi

post(){
	cd ~/Web/blog
	wait
	subl . 
	wait 
	title=$(pwd)/_posts/$(date +%Y-%m-%d)-post.md
	touch $title
	echo -e '---\nlayout: post\ntitle: "" \n\n---' > $title
	subl $title -a
}


note(){
	cd ~/Web/blog
	wait
	subl . 
	wait 
	title=$(pwd)/_notes/$(date +%Y-%m-%d)-note.md
	touch $title 
	echo -e '---\nlayout: note\ntitle: "" \n\n---' > $title
	subl $title -a
}

push(){

	echo  -e "\e[38;5;222mPushing site to GitHub Pages..\e[0m"
	echo ""
	cd ~/Web/blog
	git add .
	git commit -m "$(date)"
	git config credential.username "cricketball"
	wait
	git push origin master
	wait
	git config credential.username "abhishekbalam"
}

build(){
	echo  -e "\e[38;5;222mBuilding Jekyll site.\e[0m"
	echo ""
	cd ~/Web/blog
	jekyll build
}

compile(){
	build
	surge _site -d journal.abhishekbalam.xyz
}


serve(){

	echo  -e "\e[38;5;222mRunning Jekyll site locally...\e[0m"
	echo ""
	cd ~/Web/blog
	jekyll serve --watch
	# xdg-open http://127.0.0.1:4000 &

}


while [ $# -gt 0 ]
do
    case "$1" in
       	open)  subl ~/Web/blog;;
		files) nautilus ~/Web/blog;;
		post) post;;
		note) note;;
		push) push;;
		publish) compile;;
		demo) serve;;
		build) build;;
		view) xdg-open http://journal.abhishekbalam.xyz& ;;
		-h)  help;;
		*)  
			help_msg "\e[31m\e[1mWrong arguments!\e[0m"
			exit 1;
			break;
 	esac
    shift
done
